version: '2.0'
services:
  tron-node:
    image: caeldock/tron-node
    hostname: tron-node
    ports:
      - 18888
      - 50051
    tty: true
    working_dir: /java-tron/build/libs
    command: java -jar java-tron.jar
    networks:
      - esnet

  # tron-node-2:
  #   image: caeldock/tron-node
  #   hostname: tron-node
  #   expose:
  #     - 18888
  #     - 50051
  #   tty: true
  #   working_dir: /build/libs
  #   command: java -jar java-tron --witness
  #   links:
  #     - tron-node


  cassandra-1:
    hostname: cassandra-1
    image: cassandra:3.11
    ports:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    working_dir: /scripts

    tty: true
    volumes:
      - ./cassandra/cass.sh:/scripts/cass.sh
      - ./cassandra/cass.sql:/scripts/cass.sql
      - cassdata1:/usr/share/cassandra/data
    networks:
      - esnet

  cassandra-2:
    hostname: cassandra-2
    image: cassandra:3.11
    environment:
      - CASSANDRA_SEEDS=cassandra-1
    links:
      - cassandra-1
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    tty: true
    volumes:
      - cassdata2:/usr/share/cassandra/data
    networks:
      - esnet


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # this setting forces dev mode remove for bootstrap checks
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-methods=OPTIONS, HEAD, GET, POST
    ulimits:
      memlock:
        soft: -1
        hard: -1
    working_dir: /scripts
    volumes:
      - ./elastic/mappings/:/scripts/mappings/
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - esnet

  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  #   container_name: elasticsearch2
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata2:/usr/share/elasticsearch/data
  #   networks:
  #     - esnet

  service-layer:
    image: caeldock/service-layer-node
    working_dir: /block-chain-explorer
    tty: true
    links:
      - cassandra-1
      - cassandra-2
      - elasticsearch
      - tron-node
    networks:
      - esnet

volumes:
  cassdata1:
    driver: local
  cassdata2:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
