version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    #   - ./graphs:/usr/share/kibana/config/graphs.json
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - esnet
